complexity:
  ComplexCondition:
    active: false
  CyclomaticComplexMethod:
    active: false
  LargeClass:
    excludes: '**/src/test/**/*.kt'
  LongMethod:
    active: false
  LongParameterList:
    active: false
  TooManyFunctions:
    active: false

empty-blocks:
  EmptyFunctionBlock:
    active: false

exceptions:
  SwallowedException:
    ignoredExceptionTypes:
      ['NumberFormatException', 'JsonPatchApplicationException', 'IllegalArgumentException', 'TimeoutException']
    excludes: '**/src/test/**/*.kt'
  TooGenericExceptionCaught:
    active: false
  TooGenericExceptionThrown:
    excludes: '**/src/test/**/*.kt'

naming:
  ConstructorParameterNaming:
    active: false
  InvalidPackageDeclaration:
    active: true
  MatchingDeclarationName:
    active: false
  TopLevelPropertyNaming:
    active: false
  VariableNaming:
    active: false

performance:
  active: false

style:
  DestructuringDeclarationWithTooManyEntries:
    active: false
  DoubleNegativeLambda:
    active: true
  ExplicitItLambdaParameter:
    active: true
  ExpressionBodySyntax:
    active: true
  ForbiddenAnnotation:
    active: true
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
  MultilineLambdaItParameter:
    active: true
    excludes: '**/src/test/**/*.kt'
  NewLineAtEndOfFile:
    active: false
  ReturnCount:
    active: false
  ThrowsCount:
    active: false
  UnnecessaryAbstractClass:
    active: false
  UnnecessaryBracesAroundTrailingLambda:
    active: true
  UnnecessaryLet:
    active: false
  UnusedImports:
    active: true
  UseAnyOrNoneInsteadOfFind:
    active: true
  UseLet:
    active: true

potential-bugs:
  CastNullableToNonNullableType:
    active: true
    excludes: '**/src/test/**/*.kt'
  MissingPackageDeclaration:
    active: true
    excludes:
      - '**/*.kts'
  PropertyUsedBeforeDeclaration:
    active: true
  # Temporarily disable due to false positives: https://github.com/detekt/detekt/issues/6129
  UnreachableCode:
    active: false
  # Disable until we've resolved, got https://trello.com/c/pJKhQth6/112-remove-instances-of for it
  UnsafeCallOnNullableType:
    active: false
