name: Normalise audio files
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: apt install
        run: |
          sudo apt-get update
          sudo apt-get install normalize-audio
      - name: normalise
        run: |
          FILES=$(ls src/main/resources/wav)
          normalize-audio $FILES
      - name: commit
        uses: EndBug/add-and-commit@v9
        if: github.ref == 'refs/heads/main'
        with:
          add: 'src/main/resources/*'
          message: "Update audio files"