name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g. v5.0.0)'
        required: true
      name:
        description: 'Release name'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - name: Build JAR
        env:
          AWS_SYNC: ${{ secrets.AWS_SYNC }}
          AWS_LOGS: ${{ secrets.AWS_LOGS }}
        run: |
          echo -n $AWS_LOGS > src/main/resources/AWS_LOGS
          echo -n $AWS_SYNC > src/main/resources/AWS_SYNC
          ls src/main/resources
          ./gradlew jar --info
      - name: Rename JAR
        run: |
          suffix="${{ github.event.inputs.version }}"
          updatedSuffix="${suffix//./_}"
          mv "build/libs/Dartzee.jar" "build/libs/Dartzee_$updatedSuffix.jar"
          ls build/libs
          export CHANGELOG=$(awk "/--------- ${{ github.event.inputs.version }} ---------/,/coverage/" src/main/resources/ChangeLog)
          echo $CHANGELOG
      - name: Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "build/libs/*.jar"
          commit: main
          name: ${{ github.event.inputs.name }}
          tag: ${{ github.event.inputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: 'Automated release'
