name: 'Terraform'
on: push
jobs:
  terraform:
    name: 'terraform'
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.3.8
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Unlock secrets'
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - name: 'Terraform Format'
        run: terraform fmt -check -recursive
      - name: 'Terraform Init'
        run: |
          cd terraform && terraform init
      - name: 'Terraform Validate'
        run: |
          cd terraform && terraform validate
      - name: 'Terraform Plan'
        run: |
          cd terraform && terraform plan --lock=false